# input = "/home/user/.Xresources"
# output_directory = "/home/user/.cache/colstract"

[wallpaper]
enable = false
# path = "/home/user/Pictures/wall.png"
# command = ["feh", "--bg-fill", "/home/user/Pictures/wall.png"]

[colors]
color0 = "#242837"
color1 = "#f14360"
color2 = "#aecc00"
color3 = "#ff9d35"
color4 = "#75b0ff"
color5 = "#c651e5"
color6 = "#4ce7ff"
color7 = "#fbe1a3"
color8 = "#7e818b"
color9 = "#ff89b5"
color10 = "#b8cc66"
color11 = "#ffc380"
color12 = "#bfd9ff"
color13 = "#d2a1e6"
color14 = "#99f5ff"
color15 = "#e3d8be"
background = "#1c1f2b"
foreground = "#cac0a9"
cursor = "#cac0a9"
